import type { Metadata } from "next";
import "./globals.css";
import { MatchProvider } from "@/context/MatchContext";
import { UserProvider } from "@/context/UserContext";
import SocketWrapper from "@/components/SocketWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
       suppressHydrationWarning={true} className="bg-background text-foreground antialiased"
      >
        <UserProvider>
          <SocketWrapper>
            <MatchProvider>
              {children}
            </MatchProvider>
          </SocketWrapper>
        </UserProvider>
      </body>
    </html>
  );
}

