import type { Metadata } from "next";
import "./globals.css";
import { MatchProvider } from "@/lib/MatchContext";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
       suppressHydrationWarning={true} className="bg-background text-foreground antialiased"
      >
        <MatchProvider >
          {children}
        </MatchProvider>
      </body>
    </html>
  );
}
